### ISSUE TITLE
Issue while using with email-templates + Nodemaier

### ISSUE THREAD

**Issue by wassimz** [ladjs/logger#6]
While I am testing the email-template plugin + nodemailer (using gmail trasnport), I got this issue

> TypeError: `meta` must be an object not a string
    at Logger.log (\node_modules\@ladjs\logger\index.js:115:13)
    at Logger.(anonymous function) [as info] (\node_modules\@ladjs\logger\index.js:70:14)
    at Object.<anonymous>.module.exports._logFunc.args [as _logFunc] (node_modules\nodemailer\lib\shared\index.js:108:18)
    at Object.response.(anonymous function).args [as info] (node_modules\nodemailer\lib\shared\index.js:141:28)
    at SMTPConnection._onConnect (\node_modules\nodemailer\lib\smtp-connection\index.js:467:21)

This happens when nodemailer try to log information using this module.

Any hints ??

**Comment by OmgImAlexis** [comment]
Can you please provide us a reproducible code sample so we can look further into this.

**Comment by niftylettuce** [comment]
it's because the second argument that is being passed to the logger is not an object, it's a string.

https://github.com/nodemailer/nodemailer/blob/master/lib/smtp-connection/index.js#L467-L479

we should probably interpret a second argument (and more after) that's a string passed to logger as a `util.format` instance

**Comment by niftylettuce** [comment]
I just finished writing the patch for this and will release a new version soon, and will also update email-templates.  Give me a moment

**Comment by niftylettuce** [comment]
Please upgrade to v0.0.7+ of @ladjs/logger via `npm install @ladjs/logger@latest` or `yarn add @ladjs/logger@latest`.  Also make sure you upgrade your usage of `koa-meta`, as there is a newer version released of that too `npm install koa-meta@latest` or `yarn add koa-meta@latest`.

**Comment by niftylettuce** [comment]
If you are using `@ladjs/web`, you can upgrade that as well.
